[package]
org = "nirmal"
name = "hl7v2_to_fhir"
version = "0.1.0"
distribution = "2201.4.2"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "ballerinax"
name = "health.hl7v2.utils.v2tofhirr4"
version = "1.0.0"
repository = "local"
