[package]
org = "healthcare_samples"
name = "carinbb_ballerina"
version = "1.0.0"
distribution = "2201.7.0"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "healthcare_samples"
name = "carinbb_package"
version = "1.0.0"
repository = "local"

[[dependency]]
org = "ballerinax"
name = "healthcare.fhir.r4"
version = "4.0.0"
